service: miranda-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    SECRET_KEY: ${file(.env.json):SECRET_KEY}
    ATLAS_SERVER: ${file(.env.json):ATLAS_SERVER}
    EMAIL_SENDER: ${file(.env.json):EMAIL_SENDER}
    EMAIL_PASSWORD: ${file(.env.json):EMAIL_PASSWORD}
    EMAIL_RECEIVER: ${file(.env.json):EMAIL_RECEIVER}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: "*"
